### ISSUE TITLE
Add Bean Goo

### ISSUE THREAD

**Issue by L89David** [koerismo/QOL-BEE#11]
Please, add bean goo, thanks.

**Comment by DrMeepster** [comment]
I agree that bean goo is a good idea

**Comment by L89David** [comment]
thank you @DrMeepster 
Wouldn't be nice to have MrBean core too? Also a normal Bean core.

**Comment by koerismo** [comment]
Bean goo won't be added to QOL given that it would have to be added as a style, something which I don't have the patience for when accounting for the other 500 things I have to fix. Bean goo/style/core should belong in its own repo.

**Comment by L89David** [comment]
Burh
