### ISSUE TITLE
Cutout type (SUGGESTION)

### ISSUE THREAD

**Issue by ThatOneRetro** [koerismo/QOL-BEE#17]
Not sure if you are already doing this but maybe you could create an exposed panel that has no damage with no bits of stuff on it like it was damaged but a full exposed panel as if the panel was never finished past the structure

**Comment by koerismo** [comment]
From what I understand, do you mean the exposed broken/repairing panels seen throughout the reconstructing section of the game?

**Comment by ThatOneRetro** [comment]
I mean the black or yellow panels with no debris
