### ISSUE TITLE
QOL not being worked on anymore (BUG)

### ISSUE THREAD

**Issue by ThatOneRetro** [koerismo/QOL-BEE#31]
The dev has stopped working on OOL (causes many leaks in my brain).

Best fix: Continue working
Easy fix: Will it ever be worked on again?

**Comment by koerismo** [comment]
[This might help.](https://docs.github.com/en/github/getting-started-with-github/quickstart/fork-a-repo)

**Comment by HeimlichLaboratories** [comment]
Except that the whole point of QOL is to help with people that want Overgrown to look better and don't know how to use Hammer? Or that's my pov anyway

**Comment by koerismo** [comment]
As I stated on **May 9**, this package is no longer being worked on. Anyone is allowed to fork the repository, but development will not continue.

**Comment by HeimlichLaboratories** [comment]
Well that's a shame. Good work on this anyway
