### ISSUE TITLE
The "Fern" in-game palette icon is missing (0.4.4 version)

### ISSUE THREAD

**Issue by LautaroL20** [koerismo/QOL-BEE#6]
![Fern in-game palette icon is missing](https://user-images.githubusercontent.com/12244376/82089233-a0e24e00-96c9-11ea-8553-6bb5bb98e57a.jpg)

**Comment by koerismo** [comment]
all icons for foliage are being redone for 0.4.5 with the addition of new foliage, this will be fixed.
