### ISSUE TITLE
Icons have discoloured backgrounds

### ISSUE THREAD

**Issue by CheezyPig** [koerismo/QOL-BEE#8]
They all have backgrounds that are too bright, except for the furn which is too dark.
![image](https://user-images.githubusercontent.com/22802323/82090756-1102cb00-96ee-11ea-84ec-b7a288b7ec89.png)

**Comment by koerismo** [comment]
I have made all icons transparent (haven't gotten to the foliage yet) in preparation for dark mode compatibility. Currently, without a properly implemented dark mode, this is an unfortunate side effect.
